function [theta1, theta2] = crossoverParents(parent1Theta1, ...
                                             parent2Theta1, ...
                                             parent1Theta2, ...
                                             parent2Theta2, ...
                                             mutationProbability, ...
                                             input_layer_size, ...
                                             hidden_layer_size, ...
                                             output_layer_size)
  parentsTheta1 = [ parent1Theta1(:)'; parent2Theta1(:)' ];
  parentsTheta2 = [ parent1Theta2(:)'; parent2Theta2(:)' ];
  theta1 = reshape(crossOverWithMutation(parentsTheta1, mutationProbability), ...
                   hidden_layer_size, (input_layer_size + 1));
  theta2 = reshape(crossOverWithMutation(parentsTheta2, mutationProbability), ...
                   output_layer_size, (hidden_layer_size + 1));
endfunction

function theta = crossOverWithMutation(parentsTheta, ...
                                       mutationProbability)
  theta = zeros(1, columns(parentsTheta));
  for t_i = 1:columns(theta)
    theta(t_i) = parentsTheta(randi(2), t_i);
    if (rand(1) <= mutationProbability)
      % Mutate current gene.
      parentGeneThetaAvg = (parentsTheta(1, t_i) + parentsTheta(2, t_i)) / 2;
      mutationDelta = [-1, 1](randi(2)) * parentGeneThetaAvg;
      theta(t_i) = theta(t_i) + mutationDelta;
    endif
  endfor
endfunction
